login:
  kerberos:
    - id: name1
      realm: ATHENA.MIT.EDU
      disablePAFXFAST: true

    - id: name2
      realm: ZEUS.MIT.NOEDU
      disablePAFXFAST: false

  ldap:
    - id: name3
      address: "ldaps://ldap.example.com:636"
      bindDN: "cn=admin,dc=example,dc=com"
      bindPW: "password"
      # If 389 port is specified we try to use startTLS
      startTLS: true
      # If startTLS fails do we use ldap without tls? THIS LEAKS PASSWORDS
      insecureNoSSL: false
      # If a custom certificate isn't provide, this option can be used to turn on
      # TLS certificate checks. As noted, it is insecure and shouldn't be used 
      # outside of explorative phases.
      insecureSkipVerify: false
      userDNType: "uid"
      baseDN: "dc=example,dc=com"
      # The input require a mail. If the ldapbind is only for the user this 
      # option consider only the first part of the mail 
      # (es. user@mail.com -> user)
      removeMail: true

    - id: name4
      address: "ldap://ldap.google.com:389"
      bindDN: "cn=admin,dc=google,dc=com"
      bindPW: "1234"
      # If 389 port is specified we try to use startTLS
      startTLS: false
      # If startTLS fails do we use ldap without tls? THIS LEAKS PASSWORDS
      insecureNoSSL: true
      # If a custom certificate isn't provide, this option can be used to turn on
      # TLS certificate checks. As noted, it is insecure and shouldn't be used 
      # outside of explorative phases.
      insecureSkipVerify: true
      userDNType: "uid"
      baseDN: "ou=users,dc=google,dc=com"
      # The input require a mail. If the ldapbind is only for the user this 
      # option consider only the first part of the mail 
      # (es. user@mail.com -> user)
      removeMail: true


socketPath: /tmp/macpass.sock

databasePath: ./db.sqlite
  
maxConnectionTime: 8

log: true
