login:
  - keberos:
    - id: name1
      realm: ATHENA.MIT.EDU
      disablePAFXFAST: true

    - id: name2
      realm: ATHENA.MIT.EDU
      disablePAFXFAST: true

  - ldap:
    - id: name3
      address: "ldaps://ldap.example.com:636"
      bindDN: "cn=admin,dc=example,dc=com"
      bindPW: "password"
      disablePAFXFAST: true
      # If 389 port is specified we try to use startTLS
      startTLS: true
      # If startTLS fails do we use ldap without tls? THIS LEAKS PASSWORDS
      insecureNoSSL: false
      # If a custom certificate isn't provide, this option can be used to turn on
      # TLS certificate checks. As noted, it is insecure and shouldn't be used 
      # outside of explorative phases.
      insecureSkipVerify: false


socketPath: /tmp/macpass.sock

databasePath: ./db.sqlite
  
maxConnectionTime: 8
