socket:
  path: "/tmp/macpass.sock"
  user: "user"

network:
  ip4: 192.168.1.1/24
  ip6: fe80::/10

  # How much time (in ms) to wait for a host to respond to arping
  timeout: 1000

  # Interface name. 
  inInterface: eth0

firewall:
  # Select firewall backend: [iptables, shorewall]
  type: "iptables"
  # If shorewall is the firewall, the name of the interface on shorewall (es. NET_IF)
  shorewallIF: NET_IF

# How much time to wait to do the next network scan and old entries scan. In
# seconds
iterationTime: 10

# How much time to wait to remove an host that is not respondig to arpings. In
# minutes
disconnectionTime: 10

# All the active connections are stored in a sqlite db in order to restart the
# macpassd service without losing the connections. If the path is empty this 
# feature is disabled
dbPath: "/var/db/macpassd-entries.db"

loggerPath: "/var/log/macpassd-entries.log" # not working

# The options are debug, info, warn and error
logLevel: debug
